### PR TITLE
do not build the C++ gazebo plugin if gazebo is excluded

### PR DESCRIPTION
**Pull request by doudou**
This is to allow using the Syskit-SDF functionality that is still
embedded in the package even on non-simulation systems.

Will be a no-op until https://github.com/Brazilian-Institute-of-Robotics/simulation-rock_gazebo/pull/33 is merged, i.e. can be merged independently

### CODE REVIEW

**Comment by doudou** [comment]
Ping ?

**Comment by dbcesar** [comment]
Tested on a fresh Ubuntu, it worked fine, I'm only not sure if we want to install the bin/rock-gazebo, bin/rock-gazebo-run, bin/rock-gzserver and bin/rock-gazebo-viz  when exclude the C++ gazebo plugin. See below the output of a `find . -iname  "*gazebo*"` inside the dev.bir/install on both machines: 

ff-nav manifest:
```
./bin/rock-gazebo-viz
./bin/rock-gazebo
./bin/rock-gazebo-run
./lib/ruby/2.3.0/rock/gazebo.rb
./lib/ruby/2.3.0/rock_gazebo
./lib/ruby/2.3.0/rock_gazebo.rb
```

Default manifest:
```
./bin/rock-gazebo-viz
./bin/orogen_default_rock_gazebo__ThrusterTask
./bin/rock-gazebo
./bin/orogen_default_rock_gazebo__ImuTask
./bin/orogen_default_rock_gazebo__WorldTask
./bin/rock-gazebo-run
./bin/orogen_default_rock_gazebo__LaserScanTask
./bin/orogen_default_rock_gazebo__BaseTask
./bin/orogen_default_rock_gazebo__ModelTask
./bin/orogen_default_rock_gazebo__CameraTask
./include/gazebo_thruster
./include/gazebo_thruster/GazeboThruster.hpp
./include/orocos/rock_gazebo
./include/orocos/rock_gazebo/rock_gazeboTypes.hpp
./include/orocos/rock_gazebo/transports/corba/rock_gazeboTypes.idl
./include/orocos/rock_gazebo/transports/corba/rock_gazeboTypesC.h
./include/rock_gazebo
./include/gazebo_underwater
./include/gazebo_underwater/GazeboUnderwater.hpp
./share/orogen/rock_gazebo.orogen
./share/orogen/rock_gazebo.tlb
./share/orogen/rock_gazebo.typelist
./lib/libgazebo_thruster.so
./lib/librock_gazebo.so
./lib/orocos/types/librock_gazebo-typekit-gnulinux.so
./lib/orocos/types/librock_gazebo-transport-mqueue-gnulinux.so
./lib/orocos/types/librock_gazebo-transport-typelib-gnulinux.so
./lib/orocos/types/librock_gazebo-transport-corba-gnulinux.so
./lib/orocos/librock_gazebo-tasks-gnulinux.so
./lib/libgazebo_underwater.so
./lib/pkgconfig/rock_gazebo-transport-mqueue-gnulinux.pc
./lib/pkgconfig/rock_gazebo-transport-typelib-gnulinux.pc
./lib/pkgconfig/orogen-project-rock_gazebo.pc
./lib/pkgconfig/rock_gazebo-typekit-gnulinux.pc
./lib/pkgconfig/orogen-orogen_default_rock_gazebo__ThrusterTask.pc
./lib/pkgconfig/rock_gazebo-tasks-gnulinux.pc
./lib/pkgconfig/orogen-orogen_default_rock_gazebo__ImuTask.pc
./lib/pkgconfig/orogen-orogen_default_rock_gazebo__LaserScanTask.pc
./lib/pkgconfig/orogen-orogen_default_rock_gazebo__ModelTask.pc
./lib/pkgconfig/gazebo_thruster.pc
./lib/pkgconfig/rock_gazebo-transport-corba-gnulinux.pc
./lib/pkgconfig/gazebo_underwater.pc
./lib/pkgconfig/rock_gazebo.pc
./lib/pkgconfig/orogen-orogen_default_rock_gazebo__BaseTask.pc
./lib/pkgconfig/orogen-orogen_default_rock_gazebo__CameraTask.pc
./lib/pkgconfig/orogen-orogen_default_rock_gazebo__WorldTask.pc
./lib/ruby/2.3.0/rock/gazebo.rb
./lib/ruby/2.3.0/rock_gazebo
./lib/ruby/2.3.0/rock_gazebo.rb
```

**Comment by dbcesar** [comment]
Let me know if you want me to check anything else.

**Comment by doudou** [comment]
It's a good point. rock-gazebo-viz does not need the C++ plugin. Only rock-gazebo and rock-gazebo-run.

I would leave it for now, let's merge this OK ?

**Comment by dbcesar** [comment]
Yes! Merging it.

**Pull request merged**
