### PR TITLE
Fix flat_fish model installation

### PR DESCRIPTION
**Pull request by Thomio-Watanabe**
- Change flat_fish source directory
 - Set GAZEBO_MODEL_PATH to install dir

Depends on: https://github.com/Brazilian-Institute-of-Robotics/robots-sdf-flat_fish/pull/2

### CODE REVIEW

**Comment by doudou** [comment]
Why did you change the package name to robots/sdf/... ? It is IMO really not nice (the package will probably contain more than a SDF model in the long run)

**Comment by Thomio-Watanabe** [comment]
So why we install the it in install/share/sdf  ?
What do you think we should add in this repository ? should we not create a new repository ?

**Comment by doudou** [comment]
This repository should IMO contain everything that is specific to the description of the flatfish robot. E.g. it could (and maybe should ...) include blender models, documentation, ... Let's not limit it to SDF.

**Comment by Thomio-Watanabe** [comment]
So the **robots/flat_fish/** repository should have a documentation and sdf folder in it !?

**Comment by doudou** [comment]
For instance. There's not standard there, so we make the standard ...

**Pull request closed without merging**
