### PR TITLE
Remove obsolete stuff

### PR DESCRIPTION
**Pull request by doudou**

### CODE REVIEW

**Comment by doudou** [comment]
Ping

**Comment by doudou** [comment]
Mmmmm ... while very funny, I'm not sure whether I can interepret this as "I checked it out, and it looks just fine" ...

**Comment by leifole** [comment]
Sometimes you "ping" hard and the ball comes back to you without any activity from the other side (and without proper "pong")...
And no, I haven't checked it out since I am not familiar with the flat_fish package set. Just wanted to lift the mood. But maybe that draw the attention of someone, who is familiar with the package set and now happily starts checking the changes ;-)

**Comment by doudou** [comment]
Ping @Brazilian-Institute-of-Robotics/flatfish-br

**Comment by g-arjones** [comment]
It builds ok but haven't run any unit tests so I am not sure about the patches. Any specifics you would like me to check? Looking forward to closing this PRs too..

**Comment by doudou** [comment]
Just wanted to be sure that someone tested it on another machine, especially the collada stuff.

Thanks !

**Pull request merged**
