### PR TITLE
Gazebo7

### PR DESCRIPTION
**Pull request by g-arjones**
Shouldn't we merge this? Right now for our buildconf to work we have to merge at least 3 different branches..

### CODE REVIEW

**Comment by doudou** [comment]
Good point. Could you comment on the PR about sdformat4 on the rock package set as well ? I'm waiting for someone to review it before I merge.

Need to remove the last commit from this branch first, svn must NOT be defined by custom package sets, it's part of autoproj's default osdeps. The svn thing is broken because of a bug in autoproj (which I can't release because nobody looks into https://github.com/rock-core/package_set/pull/93)

**Comment by g-arjones** [comment]
No problem. I think installing svn manually until autoproj is fixed is a better workaround than having this (the last commit).

**Comment by doudou** [comment]
Could you remove the SVN commit and rebase against the new master (there's a conflict :(). Then merge !

**Comment by g-arjones** [comment]
The svn commit was the source of the conflict. Going to merge.

**Pull request merged**
