### PR TITLE
change package name

### PR DESCRIPTION
**Pull request by gustavoneves12**
change the package gui/orogen/underwater_camera_simulation to simulation/orogen/underwater_camera

### CODE REVIEW

**Comment by doudou** [comment]
That is something you should have discussed ... 'underwater_camera' is really not precise enough. I prefer the underwater_camera_simulation greatly. (or uw_camera_simulation if you want it shorter)

**Comment by gustavoneves12** [comment]
I changed the name because the full package name contains the word simulation twice, "simulation"/orogen/underwater_camera_"simulation". In my opinion, if the package is inside the folder simulation, then the underwater_camera is a Rock Component used to simulate camera. But we can change the name again.

**Comment by doudou** [comment]
You have a point. However, while Rock's package name is the full simulation/orogen/underwater_camera, the orogen package name is only 'underwater_camera' which is too generic (e.g. the C++ namespace is called underwater_camera)

**Comment by gustavoneves12** [comment]
@doudou: I rename the package name again. I did amend commit.

**Comment by doudou** [comment]
Remove the stuff with about robots/sdf/flat_fish, this package should stay in robots/flat_fish

**Comment by gustavoneves12** [comment]
@doudou I remove robots/sdf/flat_fish

**Pull request merged**
